Added example model for TCMS
qakit/tcms pull request #1
Opened 2021-04-14 13:04 UTC by AndrewEgorov

2021-04-14 15:09 UTC, OlegZee requested changes

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/Component.cs
> +		[Required]
You can put both in one line like [Required, StringLength(50)]

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCase.cs
> +		[Key]
You don't have to put it if field name is "Id" or <TableName>Id.

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCase.cs
> +		public double Estimate { get; set; }
Consider naming EstimateHr so that all know the units.

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/Attachment.cs
> +		[ForeignKey("TestCaseStepId")]
According to https://entityframework.net/foreign-key it should be:
```
[ForeighKey("Step")]
public int StepId { get; set; }
public TestCaseStep Step { get; set; }
```

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/Component.cs
> +		public int? ParentComponentId { get; set; }
What do you think if we limit nesting by factor of say 2? I would consider several other approaches to store hierarchy relation and I would like to analyze use cases as well.

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCasePriority.cs
> +	public class TestCasePriority
May it mean "importance" of the test case?
Can we use Tags instead so that we have more generic mechanism to classify the cases?

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCaseStatus.cs
> +		public string Description { get; set; }
Missing public bool IsApproved field for marking "approve" statuses.

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCaseStep.cs
> +		//Do we need it? E.g. to show correctly in UI
I think yes. However we can make the whole testcase containing only precondition steps for other tests.

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCaseStep.cs
> +		public virtual TestCase TestCase { get; set; }
I don't see backward link to Attachment.
Also as soon they are related as 1:1 would it be reasonable to add byte[] Content field in step?

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCaseType.cs
> +	public class TestCaseType
This seems like least important classification maily for searching. Is it correct?
Can we use Tags for that?

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/User.cs
> +	public class User
Please see how to define our own User entity [here](https://entityframework.net/knowledge-base/20104289/foreign-key-to-microsoft-aspnet-identity-entityframework-identityuser-).
That way you don't need regular "user" fields.

2021-04-14 15:09 UTC, OlegZee commented on src/Data/Models/TestCaseStep.cs
> +		public int TestCaseStepId { get; set; }
We need an Ordinal field as well to define the order of the steps.

2021-04-15 02:13 UTC, AndrewEgorov commented on src/Data/Models/TestCase.cs
> +		[Key]
I know :) added to be more informative i think. Removed from code

2021-04-15 02:16 UTC, AndrewEgorov commented on src/Data/Models/Component.cs
> +		[Required]
Done

2021-04-15 02:26 UTC, AndrewEgorov commented on src/Data/Models/Attachment.cs
> +		[ForeignKey("TestCaseStepId")]
Oh, yes. Fixed everywhere

2021-04-15 02:26 UTC, AndrewEgorov commented on src/Data/Models/TestCasePriority.cs
> +	public class TestCasePriority
How tag can be used in this situation?

2021-04-15 02:28 UTC, AndrewEgorov commented on src/Data/Models/TestCaseStatus.cs
> +		public string Description { get; set; }
This table is suppose to contain several statuses and idea to store status of the case here. E.g. Proposed (any newly added test case), Approved (which was revewed and approved by qa lead/manager), Require Update (case which require update of steps or anything).

2021-04-15 02:32 UTC, AndrewEgorov commented on src/Data/Models/TestCaseStep.cs
> +		public virtual TestCase TestCase { get; set; }
* Also as soon they are related as 1:1 would it be reasonable to add byte[] Content field in step? - for what purpose? They related 1 to many. 1 step can contain many attachments. 

Fixed: added navigation property to Attachments collection

2021-04-15 02:33 UTC, AndrewEgorov commented on src/Data/Models/TestCaseType.cs
> +	public class TestCaseType
Mostly for search and categorization. Can you explain how tags can be used instead of test case type and priority?

2021-04-15 05:46 UTC, merged